language: cpp

compiler:
  - gcc

before_install:
  - sh -c "sudo apt-get install -qq build-essential curl libarchive-dev libexpat1-dev zlib1g-dev libcurl4-openssl-dev mingw-w64 gcc-mingw-w64-i686 g++-mingw-w64-i686 binutils-mingw-w64-i686 mingw-w64-dev python-software-properties"
  - sh -c "sudo add-apt-repository ppa:kalakris/cmake -y; sudo apt-get update -qq; sudo apt-get install -qq cmake"
  - sh -c "sudo mv cmake/sal.h /usr/i686-w64-mingw32/include/"

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-cross-mingw32-linux.cmake ..

script: make

deploy:
  provider: releases
  api-key: 
    secure: "GGtmz5ZtMmYFPFynNGTlQRMYb8yPDIDUZTckNh+BQFHm7zcAonTb/CkMI/idhOrJQ/FAOb0nMcy3y3d0WA/EhG+Dl/D7cbhWPE7o9nwXGPo5/E/fNzltqKQlkd+r2cCiSlHuZLE2A3n2hNrJcvRbxEuHSXmj5bQE9kNvU3c8Yik="
  file: WinK760.exe
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
